// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Math from "math/src/Math.bs.js";
import * as React from "react";
import ReactSvg from "./assets/react.svg";

import './App.css'
;

var reactLogo = ReactSvg;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, String($$Math.addFloat(2.3, 3.5)));
}

var make = App;

export {
  reactLogo ,
  make ,
}
/*  Not a pure module */
